### ISSUE TITLE
Feature request / question for commit details

### ISSUE THREAD

**Issue by alex4200** [CMUSTRUDEL/strudel.scraper#21]
I need details on commits, and therefore I added some lines to the code to implement this functionality:

```
    @api('repos/%s/commits/%s', paginate=True)
    def repo_commit_detail(self, repo_slug, commit_hash):
        """Get details for a given commit."""
        # https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#get-a-commit
        return repo_slug, commit_hash
```

However, this returns a object like

`<generator object VCSAPI.request at 0x10a1e5890>`

How to convert that to a json/dict object?

**Comment by user2589** [comment]
added as a feature in 1.4.0. Example:
```
api.repo_commit('cmustrudel/strudel.scraper', '6adbcd5fbbee057dae4802a2b7099f3f35999e4a')
```

Note: github API is rate limited, working with commit data in bulk is easier by cloning the repository and then working with local git (eg using gitpython or pygit2)

**Comment by user2589** [comment]
oh, btw, the original code didn't work because this API doesn't need pagination. Simply removing `paginate=True` would fix it.
